### ISSUE TITLE
请问你这个版本的怎么用

### ISSUE THREAD

**Issue by drcayman** [FlowerWrong/tun2socks#1]

**Comment by drcayman** [comment]
你这个版本的tun2socks  跟  gotun2sock 类似吗   udp功能是否已经实现了呢

**Comment by drcayman** [comment]
@FlowerWrong

**Comment by FlowerWrong** [comment]
现在还不可用，正在添加udp via socks5功能。如果你使用tcp dns，那是可以的。

**Comment by FlowerWrong** [comment]
pre released [version](https://github.com/FlowerWrong/tun2socks/releases)
See more readme and wiki.
