### ISSUE TITLE
新增dns-mode需求建议

### ISSUE THREAD

**Issue by zdm2008** [FlowerWrong/tun2socks#11]
测试发现tun2socks只是通过DNS来实现分流的，这种情况如果正常上网，通过域名请求连接则可以符合需求；但是直接远程IP地址的时候，并不会使用geoip来实现地区分流。

建议：可否在[dns]配置下增加一个，dns-mode = disable这样的参数，使得tun2socks本身不做任何DNS设置，而是由用户自己在操作系统层手动增加tap的路由？

**Comment by zdm2008** [comment]
上面的建议不是很好的办法，因为导入一个国家/地区的IP段到操作系统的路由表，花费的时候太长，开销很大。
可者您看看还有什么方法，可以实现直连远程IP，也能做到使用geoip来实现地区分流？

**Comment by zdm2008** [comment]
你看看这个项目是否可以用fake gateway来解决这个问题？
https://github.com/jackpal/gateway

**Comment by FlowerWrong** [comment]
可以使用route配置，https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L35

**Comment by FlowerWrong** [comment]
目前我能想到的就是这两种方式，tun2socks都支持。https://github.com/jackpal/gateway 看了下，只是拿到default gateway，没什么用。
