### ISSUE TITLE
想了解下这个项目的 DNS 相关的工作原理

### ISSUE THREAD

**Issue by LuoZijun** [FlowerWrong/tun2socks#12]
如题: 想了解下这个项目的 DNS 相关的工作原理， 如果作者有时间的话，不知是否能讲解下。

**Comment by FlowerWrong** [comment]
@LuoZijun 你看下这里能否明白。https://github.com/FlowerWrong/tun2socks/wiki#dns-mode

**Comment by LuoZijun** [comment]
@FlowerWrong 

`fake(default) ` 模式会在本地创建一个 `DNS Server` 服务，这个是出于什么考量呢？使用场景是什么呢？

**Comment by FlowerWrong** [comment]
如果需要根据ip将流量导入到tun设备，有两种模式：
1. 路由表 [example](https://github.com/FlowerWrong/ip2socks/blob/master/scripts/darwin_down_utun.sh)，存在的问题是路由表数量大。
2. fake ip, eg `www.google.com -> 198.18.26.133`，本地跑一个dns服务器代替系统的dns服务器，更具域名配置规则返回fake ip，eg [tun2socks cofnig.ini](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L81)，然后利用路由表将fake ip段的流量都导入到tun

```
198.18.0.0      0.0.0.0         255.254.0.0     U         0 0          0 tun0
198.18.0.0      0.0.0.0         255.254.0.0     U         0 0          0 tun0
```

**Comment by LuoZijun** [comment]
@FlowerWrong 

那么假设我访问 `www.example.com` 使用的是 `IP` 访问，那么你这个就无效咯？

**Comment by FlowerWrong** [comment]
自带了一个路由配置，支持单ip和ip cidr，当然，也可以手动添加路由表。
https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L37

**Comment by LuoZijun** [comment]
在本地系统搭建一个 `DNS SERVER`:

路由表配置:

```bash
sudo route delete 0.0.0.0
# 所有的默认走代理
sudo route add 0.0.0.0 gw -interface tun
sudo route add VPN_SERVER gw -interface en0
```
本地 DNS 服务:

```rust
// Local DNS
let dns_resolver = DNS_SERVER::new("8.8.8.8");

// 不走的代理的IP列表 ( 比如 CN IPs )
let user_routing_table = ["39.22.22.22"];

fn lookup(ip: &str) -> Option<Ipv4Addr> {
    let ips = dns_resolver.lookup().collect::<Vec<Ipv4Addr>>();
    for ip in ips {
        if user_routing_table.contains(ip) {
            // 默认优先 返回 可以不用 走代理的 IP
             return Some(ip);
        }
   }
   if ips.len() > 0 {
        // 返回 需要走代理的 IP.
        return Some(ips[0]);
   } else {
       return None
   }
}

```

协议栈:

```rust
// tcp/ip and udp/ip stack

type Packet = Ipv4Packet | Ipv6Packet;


let default_output_interface = Interface::with_name("en0");
let tun_interface = Interface::with_name("utun10");

impl Stack {
    pub fn send(packet: Packet) {
        if user_routing_table.contains(packet.dst_ip) {
            // 不走代理
            default_output_interface.send(packet);
        } else {
            // 走代理
           tun_interface.send(packet);
        }
    }
}

fn main (){
      let stack = Stack::new();
      stack.send(packet)
}


```
这样一来，会不会更简单些 ？

**Comment by FlowerWrong** [comment]
我不确定是否可行，你可以做下测试。
另外，即使可行，我仍然觉得rake ip是目前的最佳方案。

**Comment by LuoZijun** [comment]
@FlowerWrong 

`rake ip` 是什么意思？

嗯，流量分流（走代理与不走代理）这是 `
https://github.com/LuoZijun/exodus` 准备要做的（目前会代理全部）。

发这个主要是探讨下。

**Comment by LuoZijun** [comment]
@FlowerWrong 

我看到你也使用了 `OpenVPN/tab-windows` 这个驱动，
你有没有兴趣写个 `Rust` 的绑定呀？

手上没有 windows , windows 的代码我都是在盲写。

**Comment by FlowerWrong** [comment]
rake ip means `www.google.com -> 198.18.26.133`， `192.18.0.0/15`是网络基准测试
我几乎不用windows。你可以参考https://github.com/songgao/water 来写。

**Comment by LuoZijun** [comment]
@FlowerWrong 

我知道他那个， `unix-like` 的 `tuntap` 我已经搞定过了。

`windows` 的那个 `tun drive` 他也是 使用 `OpenVPN/tap-windows` 来的，需要你先安装。

我希望的是这个是集成在 vpn 程序里面，不需要用户介入。这就是为什么我需要 一个 `rust` 对 `OpenVPN/tap-windows` 的绑定。

后面有时间我会做这个。

**Comment by FlowerWrong** [comment]
装一个不是很麻烦，集成了反而没有必要，各自干各自的事情。或者和你的exe一起打包安装，类似openvpn安装机制。

**Comment by LuoZijun** [comment]
@FlowerWrong 

我是不觉得麻烦呀，用户会会觉得麻烦嘛，他们绝大部分是不懂的。

你想想 如果 不是 `DHCP` 帮助自动配置了 `DNS/Gateway` (现在有一个发行版把  socks5 proxy 也加入进去了 ) 这些 ， 普通用户上个网估计都很困难。

你可以看看 我的 ExodusVPN ，只需要一行命令启动就行，什么 IP 配置呀，这些都是从 VPN Server 自动获取的，比你的要简单多咯。

猿类嘛，就是解决人类不想解决的问题的～～

**Comment by LuoZijun** [comment]
`tap-windows` 和 `vpn` 一起打包安装就是我要做的，这就是为什么要写个 `rust-tap-windows` 绑定嘛，让 `VPN` 自己探测 `tap` ，并决定是否需要装。

**Comment by FlowerWrong** [comment]
> 让 VPN 自己探测 tap ，并决定是否需要装

ok, [this line](https://github.com/songgao/water/blob/master/syscalls_windows.go#L145) may help you.

**Comment by LuoZijun** [comment]
thx.

**Comment by raintean** [comment]
@LuoZijun 程序内部二进制包含一个 tap 的驱动   然后释放 静默安装  并没有什么麻烦的地方,  实验过...  即使不懂电脑的人...  也能顺利安装...

**Comment by LuoZijun** [comment]
@raintean 我也是这么想的，主要我几乎没有使用Windows，所以不太清楚。有时间我会试试。

**Comment by LuoZijun** [comment]
@raintean 当然如果你能给一个rust的范例那就更好了。
