### ISSUE TITLE
export more c api

### ISSUE THREAD

**Issue by FlowerWrong** [FlowerWrong/tun2socks#14]
* [x] StartTun2socks
* [x] StopTun2socks
* [x] reloadConfig
* [x] setSystemDNSServer
* [x] resetSystemDNSServer
* [ ] flow, dns info

**Comment by zdm2008** [comment]
c api 没有closeTun2socks这样的方法吗？

**Comment by FlowerWrong** [comment]
没有，上层应用自己解决。

**Comment by zdm2008** [comment]
上层应用自己如何解决？
