### ISSUE TITLE
Not one issue, only one question!

### ISSUE THREAD

**Issue by fffmonkeyking** [FlowerWrong/tun2socks#17]
大牛，
     如果对同一客户端，我想做到，当客户端访问不同的应用（不同的应用IP），tun2socks能把相应的访问导到不同的 ssserver上。
    举个例子：
    1、我在客户端启动1个tun2socks（只能启动1个）；然后在客户端启动2个sslocal（sslocal1：127.0.0.1:1081，sslocal2：127.0.0.1:1082），其中sslocal1的远端ssserver为183.232.29.1:8388，sslocal2的远端ssserver为183.232.29.2:8388；
    2、192.168.2.1是远端ssserver 183.232.29.1:8388后的应用，192.168.2.2是远端ssserver 183.232.29.2:8388后的应用；
    3、当客户端访问192.168.2.1时，tun2socks收集数据，当发现目标ip是192.168.2.1时，tun2socks将数据转发到sslocal1，然后sslocal1转发数据到183.232.29.1:8388，然后183.232.29.1:8388转发数据到192.168.2.1；
    4、当客户端访问192.168.2.2时，tun2socks收集数据，当发现目标ip是192.168.2.2时，tun2socks将数据转发到sslocal2，然后sslocal2转发数据到183.232.29.2:8388，然后183.232.29.2:8388转发数据到192.168.2.2；

    如上，tun2socks的config文件怎么配置？还是说，这样的拓扑tun2socks目前无法实现？感谢大神回复

**Comment by FlowerWrong** [comment]
目前都是按照域名规则，不支持这种操作，要支持理论上也是可以的。

**Comment by fffmonkeyking** [comment]
理论上也是可以的？

是需要修改代码么？

我先研究一下你的代码

**Comment by FlowerWrong** [comment]
需要，有不少工作要做，相当于一种全新的模式。

**Comment by zdm2008** [comment]
这个模式建议的不错，还可以用geoip来匹配，可实现美国的IP转到美国的proxy上，日本的转发到日本的proxy上，感谢fffmonkeyking脑洞打开。

另外，这个项目可否增加成员，我也想参与开发。

**Comment by FlowerWrong** [comment]
> 还可以用geoip来匹配，可实现美国的IP转到美国的proxy上

这个是支持的。[config](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L620) ，前提也是基于域名解析。

**Comment by fffmonkeyking** [comment]
嗯哈。

我还在考虑：
1、流量分发由  tun2socks来实现：
优点：实现应该比较简单一下，架构会比较清晰
缺点：客户端需要启多个sslocal

2、流量分发由  sslocal来实现：
优点：客户端只需要启多1个sslocal
缺点：实现应该比较麻烦一下，架构不太清晰

**Comment by zdm2008** [comment]
config下的[rule] 可以有多个吗？

**Comment by FlowerWrong** [comment]
@zdm2008 只能一个。

**Comment by zdm2008** [comment]
@FlowerWrong 那如何实现根据geoip来转发目标IP到不同的server上去呢？

**Comment by FlowerWrong** [comment]
[rule]只有一个，但是[pattern]可以有多个. [配置demo](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L633-L637)

```
[pattern "proxy-country-us"]
proxy = B
scheme = IP-COUNTRY
v = US

[pattern "proxy-country-hk"]
proxy = A
scheme = IP-COUNTRY
v = HK
```

**Comment by ffeimkii** [comment]
rule下的pattern有先后顺序么？
pattern下没有proxy = x就是相当于不走代理吧。

其实想问的是在pattern段最后加上：
[pattern "globe"]
proxy = B
scheme = IP-CIDR
v = 0.0.0.0/0
rule下加入：
pattern = globe

可以实现不在黑白名单内的走代理嘛？

**Comment by FlowerWrong** [comment]
> rule下的pattern有先后顺序么？

有的

> pattern下没有proxy = x就是相当于不走代理吧。

是的

> 可以实现不在黑白名单内的走代理嘛？

不用那么麻烦，直接指定`final`，[config.example.ini#L790](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L790)
