### ISSUE TITLE
high Idle Wakeup

### ISSUE THREAD

**Issue by Contextualist** [FlowerWrong/tun2socks#20]
On macOS Activity Monitor, tun2socks constantly has a high **Idle Wakeup**. Even at light load (browsing web, etc.), the value reaches hundreds. Sometimes it soars up to a thousand. In comparison, other processes maintain a idle wakeup below ten, and occassionally serveral dozens. 

I see that network IO demands lots of syscalls, but idle wakeup for tun2socks seems too high to be reasonable.

**Comment by FlowerWrong** [comment]
This is a bug of [netstack](https://github.com/FlowerWrong/netstack), I am finding it.

see [echo demo](https://github.com/FlowerWrong/netstack/blob/master/cmd/main.go)

```
sudo go run cmd/main.go any 10.0.0.2 8090

telnet 10.0.0.2 8090
```

**Comment by FlowerWrong** [comment]
It may be a bug of golang.
I am using [kone](https://github.com/FlowerWrong/kone) without netstack, also high idle wakeup.

`wrk -t4 -c10 -d10s http://google.com`

**Comment by FlowerWrong** [comment]
I think it is a bug of golang.
Now, I am using [FlowerWrong/netstack/tree/smart](https://github.com/FlowerWrong/netstack/tree/smart) branch with `poll`, also high Idle wakeup.
