### ISSUE TITLE
not an issue, feature suggestion: support for br insterfaces

### ISSUE THREAD

**Issue by tonsimple** [FlowerWrong/tun2socks#22]
Hi! 
a small question: would it be possible to support creation and use of bridge (br) interfaces instead of tun interfaces?

Usecase:
using it in conjunction with firejail to easily confine programs to environment where their traffic (TCP+UDP) is confined to SOCKS5 proxy with minimum effort and no routing table messing (useful for environments that already have complex routing and 2+ VPNs with TUN interfaces going)

if tun2socks supported br it would be just a matter of passing --net=brX to firejail at jailed program start.

Program won't be able to bypass proxy unless explicitly allowed by the tun2socks (as per config example) unless it's "malicious enough" to break firejail.

**Comment by FlowerWrong** [comment]
I have not used firejail, I will have a try later.

**Comment by aluvare** [comment]
If you want to have the availability to add the interface to a bridge, you will need use a tap interface instead a tun.

The bridges work at L2 and the TUN devices work at L3. 

Tun is a L3 interface, Tap is a L2 interface.

**Comment by FlowerWrong** [comment]
linux only, so drop this feature.
