### ISSUE TITLE
ins的图片刷不出来。。。

### ISSUE THREAD

**Issue by myrshfrs** [FlowerWrong/tun2socks#24]
``2018/04/01 22:26:28 table.go:129: [dns] hijack www.instagram.com -> 198.19.37.222
2018/04/01 22:26:28 fake.go:151: [dns] -------------------------- www.instagram.com via proxy B is a proxy domain config it????
2018/04/01 22:26:28 table.go:129: [dns] hijack connect.facebook.net -> 198.18.48.238
2018/04/01 22:26:29 fake.go:53: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:29 table.go:129: [dns] hijack ent-shasta-rrs.symantec.com -> 198.18.83.237
2018/04/01 22:26:29 fake.go:151: [dns] -------------------------- ent-shasta-rrs.symantec.com via proxy B is a proxy domain config it????
2018/04/01 22:26:29 table.go:129: [dns] hijack staticxx.facebook.com -> 198.18.54.252
2018/04/01 22:26:29 fake.go:53: [dns] resolve staticxx.facebook.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:30 fake.go:53: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:30 fake.go:53: [dns] resolve staticxx.facebook.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:31 fake.go:53: [dns] resolve scontent-vie1-1.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:31 fake.go:53: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:31 fake.go:155: [dns] -------------------------- dot.gate.panda.tv is a non-proxy-domain config it????
2018/04/01 22:26:31 fake.go:155: [dns] -------------------------- 1st.appalarget6.ourglb0.com is a non-proxy-domain config it????
2018/04/01 22:26:31 fake.go:53: [dns] resolve staticxx.facebook.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:32 fake.go:53: [dns] resolve scontent-vie1-1.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:32 fake.go:48: [dns] resolve www.instagram.com. on 114.114.114.114:53 failed: read udp 192.168.3.2:53562->114.114.114.114:53: i/o timeout
2018/04/01 22:26:33 fake.go:53: [dns] resolve scontent-vie1-1.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:33 fake.go:53: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:33 fake.go:53: [dns] resolve staticxx.facebook.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:33 fake.go:48: [dns] resolve connect.facebook.net. on 114.114.114.114:53 failed: read udp 192.168.3.2:62585->114.114.114.114:53: i/o timeout
2018/04/01 22:26:34 fake.go:48: [dns] resolve connect.facebook.net. on 223.5.5.5:53 failed: read udp 192.168.3.2:62586->223.5.5.5:53: i/o timeout
2018/04/01 22:26:34 fake.go:84: [dns] query connect.facebook.net. failed
2018/04/01 22:26:34 fake.go:53: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:34 fake.go:48: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:56141->223.5.5.5:53: i/o timeout
2018/04/01 22:26:34 fake.go:84: [dns] query scontent-hkg3-2.cdninstagram.com. failed
2018/04/01 22:26:34 fake.go:53: [dns] resolve staticxx.facebook.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:34 fake.go:48: [dns] resolve staticxx.facebook.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:54221->223.5.5.5:53: i/o timeout
2018/04/01 22:26:34 fake.go:84: [dns] query staticxx.facebook.com. failed
2018/04/01 22:26:34 fake.go:48: [dns] resolve connect.facebook.net. on 114.114.114.114:53 failed: read udp 192.168.3.2:54222->114.114.114.114:53: i/o timeout
2018/04/01 22:26:35 fake.go:53: [dns] resolve scontent-vie1-1.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:35 fake.go:48: [dns] resolve connect.facebook.net. on 223.5.5.5:53 failed: read udp 192.168.3.2:54223->223.5.5.5:53: i/o timeout
2018/04/01 22:26:35 fake.go:84: [dns] query connect.facebook.net. failed
2018/04/01 22:26:35 fake.go:48: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:54225->223.5.5.5:53: i/o timeout
2018/04/01 22:26:35 fake.go:84: [dns] query scontent-hkg3-2.cdninstagram.com. failed
2018/04/01 22:26:35 fake.go:48: [dns] resolve staticxx.facebook.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:54227->223.5.5.5:53: i/o timeout
2018/04/01 22:26:35 fake.go:84: [dns] query staticxx.facebook.com. failed
2018/04/01 22:26:35 fake.go:48: [dns] resolve connect.facebook.net. on 114.114.114.114:53 failed: read udp 192.168.3.2:54228->114.114.114.114:53: i/o timeout
2018/04/01 22:26:36 fake.go:53: [dns] resolve scontent-vie1-1.cdninstagram.com. on 114.114.114.114:53 failed: code 2
2018/04/01 22:26:36 fake.go:48: [dns] resolve connect.facebook.net. on 223.5.5.5:53 failed: read udp 192.168.3.2:61981->223.5.5.5:53: i/o timeout
2018/04/01 22:26:36 fake.go:84: [dns] query connect.facebook.net. failed
2018/04/01 22:26:36 table.go:129: [dns] hijack www.facebook.com -> 198.19.33.14
2018/04/01 22:26:36 fake.go:48: [dns] resolve scontent-vie1-1.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:61982->223.5.5.5:53: i/o timeout
2018/04/01 22:26:36 fake.go:84: [dns] query scontent-vie1-1.cdninstagram.com. failed
2018/04/01 22:26:36 fake.go:48: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62763->223.5.5.5:53: i/o timeout
2018/04/01 22:26:36 fake.go:84: [dns] query scontent-hkg3-2.cdninstagram.com. failed
2018/04/01 22:26:36 fake.go:48: [dns] resolve staticxx.facebook.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62765->223.5.5.5:53: i/o timeout
2018/04/01 22:26:36 fake.go:84: [dns] query staticxx.facebook.com. failed
2018/04/01 22:26:37 fake.go:48: [dns] resolve scontent-vie1-1.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62767->223.5.5.5:53: i/o timeout
2018/04/01 22:26:37 fake.go:84: [dns] query scontent-vie1-1.cdninstagram.com. failed
2018/04/01 22:26:37 fake.go:48: [dns] resolve connect.facebook.net. on 114.114.114.114:53 failed: read udp 192.168.3.2:62768->114.114.114.114:53: i/o timeout
2018/04/01 22:26:38 fake.go:48: [dns] resolve connect.facebook.net. on 223.5.5.5:53 failed: read udp 192.168.3.2:62770->223.5.5.5:53: i/o timeout
2018/04/01 22:26:38 fake.go:84: [dns] query connect.facebook.net. failed
2018/04/01 22:26:38 fake.go:48: [dns] resolve scontent-vie1-1.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62771->223.5.5.5:53: i/o timeout
2018/04/01 22:26:38 fake.go:84: [dns] query scontent-vie1-1.cdninstagram.com. failed
2018/04/01 22:26:38 fake.go:48: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62773->223.5.5.5:53: i/o timeout
2018/04/01 22:26:38 fake.go:84: [dns] query scontent-hkg3-2.cdninstagram.com. failed
2018/04/01 22:26:38 fake.go:48: [dns] resolve staticxx.facebook.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62775->223.5.5.5:53: i/o timeout
2018/04/01 22:26:38 fake.go:84: [dns] query staticxx.facebook.com. failed
2018/04/01 22:26:39 fake.go:48: [dns] resolve connect.facebook.net. on 114.114.114.114:53 failed: read udp 192.168.3.2:62776->114.114.114.114:53: i/o timeout
2018/04/01 22:26:39 fake.go:48: [dns] resolve connect.facebook.net. on 223.5.5.5:53 failed: read udp 192.168.3.2:62777->223.5.5.5:53: i/o timeout
2018/04/01 22:26:39 fake.go:84: [dns] query connect.facebook.net. failed
2018/04/01 22:26:39 fake.go:48: [dns] resolve scontent-hkg3-2.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62779->223.5.5.5:53: i/o timeout
2018/04/01 22:26:39 fake.go:84: [dns] query scontent-hkg3-2.cdninstagram.com. failed
2018/04/01 22:26:39 fake.go:48: [dns] resolve staticxx.facebook.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62781->223.5.5.5:53: i/o timeout
2018/04/01 22:26:39 fake.go:84: [dns] query staticxx.facebook.com. failed
2018/04/01 22:26:40 fake.go:48: [dns] resolve scontent-vie1-1.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:62783->223.5.5.5:53: i/o timeout
2018/04/01 22:26:40 fake.go:84: [dns] query scontent-vie1-1.cdninstagram.com. failed
2018/04/01 22:26:41 fake.go:48: [dns] resolve scontent-vie1-1.cdninstagram.com. on 223.5.5.5:53 failed: read udp 192.168.3.2:52478->223.5.5.5:53: i/o timeout
2018/04/01 22:26:41 fake.go:84: [dns] query scontent-vie1-1.cdninstagram.com. failed

**Comment by FlowerWrong** [comment]
```
[pattern "proxy-website-keyword"]
proxy = B
scheme = DOMAIN-KEYWORD
v = instgram
v = instagram
v = cdninstagram
```
