### ISSUE TITLE
不能go get下来

### ISSUE THREAD

**Issue by guage3** [FlowerWrong/tun2socks#26]
你好，我用go get -u -v github.com/FlowerWrong/tun2socks 获取不到最新的源码，于是我用git clone 下来的缺少很多依赖目录，我尝试每个目录都去对应的git，但是编译会提示很多link错误，可以上传一个完整的目录吗?

**Comment by FlowerWrong** [comment]
可以看看readme https://github.com/FlowerWrong/tun2socks#readme 我测试过
