### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jamie2020** [FlowerWrong/tun2socks#28]
大佬你好！ 我才入门golang

我有一个疑问，希望你方便的时候解答一下！

我想通过路由表的方式进行代理，但我发现我将ip添加到了路由表走的虚拟网卡，添加进去的ip就无法访问了！Tcp Udp 都不通了

请问大佬  要如何修改配置文件才能实现？

dns模式 和 另外一个模式  都不行！  

系统:Windows7 64

**Comment by FlowerWrong** [comment]
贴一下你的配置文件，windows下测试过是正常的。

**Comment by Jamie2020** [comment]
![default](https://user-images.githubusercontent.com/39301992/40089258-5c908fae-58dd-11e8-960a-115c645cc233.PNG)

tun启动后 我手动改了一下网卡ip这些！
我将全部ip都走了虚拟网卡 只保留了dns 和socks5走本地网卡！

配置文件如下:

[dns]
# dns mode: fake or udp_relay_via_socks5, default fake, fake means google.com -> 10.192.10.126
dns-mode = udp_relay_via_socks5


[udp]
proxy = B

# define a proxy named "A"
[proxy "A"]
url = socks5://118.187.5.69:1099

# define a proxy named "B"
[proxy "B"]
url = socks5://118.187.5.69:1099
# use this proxy as default
default = yes


# rules define the order of checking pattern
[rule]

# set to a proxy for domaines that don't match any pattern
# DEFAULT VALUE: ""
final = B

**Comment by Jamie2020** [comment]
比如 我要 188.188.188.188  这个IP走虚拟网卡！那么我的路由表命令就应该是 ：
route add 188.188.188.188 198.18.0.0 metric 5
DNS模式用的:udp_relay_via_socks5
配置文件也就修改了 dns模式 和socks代理IP这2处！

路由表添加进去并确定已经走了虚拟网卡！连接188.188.188.188就会超时  连接不上！

请大佬解答该如何配置文件？

**Comment by FlowerWrong** [comment]
`118.187.5.69:1099` 这个是本地的吗？这个工具只负责倒流到socks5代理。如果不是本地的，那么你还需要`route add -host 118.187.5.69 $GATEWAY_IP`，类似这样子的命令，windows下自行替换。
