### ISSUE TITLE
issues about LICENSE and program version

### ISSUE THREAD

**Issue by MittWillson** [FlowerWrong/tun2socks#31]
有两个问题
### 开源协议
希望能添加开源协议, 没开源协议不利于使用

### 程序版本
希望可以提供 `-v` 或者 `--version` 来获取程序编译版本

另外感谢作者提供的方案

**Comment by FlowerWrong** [comment]
Thanks for your suggestion.

> LICENSE

This project has no any license, you can use it to do what you want, but it has nothing to do with me.

> Version

I add it.

```bash
sudo go run cmd/main.go -h
sudo go run cmd/main.go -v
sudo go run cmd/main.go -c=config.ini
```
