### ISSUE TITLE
connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by ffeimkii** [FlowerWrong/tun2socks#33]
windows下，一大段：

2018/06/16 13:47:51 tcp2socks.go:56: [tcp] dial r4---sn-i3belnez.googlevideo.com:443 by proxy "B" failed: dial tcp 127.0.0.1:11080: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2018/06/16 13:47:55 tcp2socks.go:56: [tcp] dial r4---sn-i3belnez.googlevideo.com:443 by proxy "B" failed: dial tcp 127.0.0.1:11080: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2018/06/16 13:47:55 tcp2socks.go:56: [tcp] dial r4---sn-npoeenee.googlevideo.com:443 by proxy "B" failed: dial tcp 127.0.0.1:11080: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.
2018/06/16 13:47:55 tcp2socks.go:56: [tcp] dial r4---sn-npoeenee.googlevideo.com:443 by proxy "B" failed: dial tcp 127.0.0.1:11080: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.

和正常log交差出现，几乎从头到尾都有这种。似乎是TcpListener监听了同样的端口，在这期间所有连接没有响应。

**Comment by ffeimkii** [comment]
netsh int ipv4 show dynamicport tcp
协议 tcp 动态端口范围
---------------------------------
启动端口        : 12000
端口数          : 40000
依然出现楼上的状况。
这动态端口范围我改过了，默认也有1w6，应该不会是端口用光。

同时还出现了：
2018/06/16 14:42:24 tcp2socks.go:56: [tcp] dial video-edge-8e6354.sjc02.hls.ttvnw.net:443 by proxy "B" failed: proxy: failed to read connect reply from SOCKS5 proxy at 127.0.0.1:11080: EOF
出现一次就是tcp timeout 期间其他动作不会执行（不能新建连接），config里timeout 要尽量短才行，毕竟转发本地。

**Comment by liukeyou** [comment]
连接复用或设置MaxIdleConnsPerHost

**Comment by ffeimkii** [comment]
更新后小试了一下，这个问题还是有发生，但是没有影响其他链接，不会出现所有链接都卡住的现象。
现在的情况是，比如打开youtube，主页部分视频的封面图不能载入，几乎不影响正在使用了。
