### ISSUE TITLE
How to provide username and password for SOCKS5?

### ISSUE THREAD

**Issue by ramazanpolat** [FlowerWrong/tun2socks#35]
I am using an external SOCKS5 proxy(not on my localhost) and it requires authentication.
How do I provide the username and password of this SOCKS5 proxy to tun2socks?

**Comment by FlowerWrong** [comment]
Now, tun2socks does not support it. I will add it later.

* [ ] SOCKS5 auth support

**Comment by FlowerWrong** [comment]
https://github.com/FlowerWrong/tun2socks/commit/7d36cdbdc25ca4dcccd9f5a17106ca5e03322532
https://github.com/FlowerWrong/gosocks/commit/30cfc3c7536bca5bb1492bc300f6735d3e09096f

[config.example.ini example](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L72)
