### ISSUE TITLE
about tun2socks high CPU load with 500Mbps

### ISSUE THREAD

**Issue by MittWillson** [FlowerWrong/tun2socks#36]
## 问题描述
我是以网页在线测速来看cpu负载的, 在测速的时候看CPU负载, 发现tun2socks负载为200%, 而ss-local负载为50%, 我是感觉这块性能确实是有点问题.

我也测试了类似的一些实现, 比如Proxifier, 测试结果是Proxifier的负载和ss-local基本持平
我也一直在看源码, 但是我能力太差始终没有思路解决这个问题, 所以过来发个issue看是否考虑下性能优化, 或者给个思路.

**Comment by MittWillson** [comment]
有个测试进展，将BufferSize和MTU都调大，比如9000, 测试下载的时候CPU会下降到原来的1/4，但是我对虚拟网卡这块的知识点不足，想请教下这样做会不会有副作用，我网上查的无论是巨型帧还是MTU都是相对于物理网卡而言，TUN我不知道会不会有同样的问题

**Comment by FlowerWrong** [comment]
我这边日常使用 [high Idle Wakeup issue](https://github.com/FlowerWrong/tun2socks/issues/20)，cpu占用极小。内存也不大。

**Comment by MittWillson** [comment]
日常使用确实如此，但是跟流量大小和CPU性能有关，比如我这边带宽能达到>300Mbps, i7 4.2Ghz, 全速下载东西的时候tun2socks能够跑到>200%, 而此时作为加解密核心的ss-local却只有50%左右的幅度

场景换到低性能机器上，双核3.3Ghz(Vmware虚拟机)，仅跑100Mbps都跑不满，因为CPU先跑满了，所以我觉得还是有很大优化空间的

**Comment by FlowerWrong** [comment]
@MittWillson 麻烦帮忙测试一下 [kone](https://github.com/FlowerWrong/kone)，使用差不多，需要手动设置系统dns为`127.0.0.1`，和tun2socks的方案有略微不同。

**Comment by MittWillson** [comment]
@FlowerWrong 测试结果 kone的cpu为ss-local的50%  比tun2socks低了近10倍

**Comment by FlowerWrong** [comment]
@MittWillson 麻烦再次测试一下，注意将本地的netstack切换到[smart branch](https://github.com/FlowerWrong/netstack/tree/smart), 该分支使用google netstack自带的blockpoll。支持darwin and linux。
