### ISSUE TITLE
make error for linux

### ISSUE THREAD

**Issue by fffmonkeyking** [FlowerWrong/tun2socks#4]
src/github.com/FlowerWrong/tun2socks# make release
GOOS=linux go build -o tun2socks_linux cmd/main.go
# github.com/FlowerWrong/tun2socks/tunnel
tunnel/udp2socks5.go:245:3: undefined: udp.UDPNatList
make: *** [release] Error 2

![Uploading image.png…]()

**Comment by FlowerWrong** [comment]
try `go get ./...` to install all dependencies of this project.

**Comment by fffmonkeyking** [comment]
src/github.com/FlowerWrong/tun2socks# go get ./...
# github.com/FlowerWrong/tun2socks/cmd/udp
cmd/udp/server.go:8:6: main redeclared in this block
	previous declaration at cmd/udp/client.go:31:6
# github.com/FlowerWrong/tun2socks/tunnel
tunnel/udp2socks5.go:245:3: undefined: udp.UDPNatList

**Comment by FlowerWrong** [comment]
You are missing [netstack](https://github.com/FlowerWrong/tun2socks/blob/master/tunnel/udp2socks5.go#L16), you can run `go get github.com/FlowerWrong/netstack` hand by hand.

Also you can follow the [readme](https://github.com/FlowerWrong/tun2socks#how-to-use-it), it worked.
