### ISSUE TITLE
../netstack/tcpip/transport/udp/udp_packet_list.go:1:1: expected 'package', found 'EOF'

### ISSUE THREAD

**Issue by skygate2012** [FlowerWrong/tun2socks#44]
Followed the readme.md but failed at step 3
 `go get ./...`
returned
```
tun2socks/stack.go:14:2: 
../netstack/tcpip/transport/udp/udp_packet_list.go:1:1: expected 'package', found 'EOF'

```

**Comment by FlowerWrong** [comment]
Sorry for this error. The netstack package is broken, you can checkout [this commit](https://github.com/FlowerWrong/netstack/commit/960b203c4bd3de09ed3b4c79991255b533b5aee6) by hand. It worked well.

**Comment by FlowerWrong** [comment]
I have fixed the master branch of netstack, you can try it now.
