### ISSUE TITLE
fail on macOS.  operation not permitted. 

### ISSUE THREAD

**Issue by lgh06** [FlowerWrong/tun2socks#45]
➜  shine ./excute-global.bash       
2018/10/24 19:16:04 main.go:37: [app] config file path is config-global.ini
2018/10/24 19:16:04 proxies.go:62: [proxies] default proxy: "B"
2018/10/24 19:16:04 tun_darwin.go:27: Create tun interface failederror in syscall.RawSyscall(syscall.SYS_CONNECT, ...): operation not permitted

ran darwin binary file from release.

**Comment by lgh06** [comment]
it worked after sudo, but no effect. 
What should I do next?  thx.

18/10/24 19:20:45 cmd.go:14: [command] route -n add -net 91.108.4.0 -netmask 255.255.252.0 -interface utun1
2018/10/24 19:20:45 cmd.go:14: [command] route -n add -net 91.108.56.0 -netmask 255.255.252.0 -interface utun1
2018/10/24 19:20:45 cmd.go:14: [command] route -n add -net 109.239.140.0 -netmask 255.255.255.0 -interface utun1
2018/10/24 19:20:45 cmd.go:14: [command] route -n add -net 149.154.160.0 -netmask 255.255.240.0 -interface utun1
2018/10/24 19:20:45 cmd.go:14: [command] route -n add -net 149.154.167.0 -netmask 255.255.255.0 -interface utun1
2018/10/24 19:20:45 cmd.go:14: [command] route -n add -host 8.8.8.8 -interface utun1
2018/10/24 19:20:45 cmd.go:14: [command] route -n add -host 4.4.4.4 -interface utun1
2018/10/24 19:20:45 main.go:95: [app] run tun2socks(0.50) success
2018/10/24 19:20:45 cmd.go:38: [shell] output Current active networkservice is Wi-Fi, C6E2D63D-FE86-4B13-920D-BCDCEA52904E
old dns is There aren't any DNS Servers set on Wi-Fi., set dns to 127.0.0.1
2018/10/24 19:20:45 dns.go:12: [dns] listen on 0.0.0.0:53

**Comment by FlowerWrong** [comment]
Did you have ran a socks server in local or in the vps?
see [socks 5 replay server config](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L73-L82)

**Comment by lgh06** [comment]
I have updated my log posted above.  
I can ensure my socks5 proxy works fine and my SwichyOmega works fine and I changed its config file to the right ip&port.  

Do I need further steps?  
 and after I control+C to stop tun2socks, I must change my DNS to previous setting manually...

**Comment by lgh06** [comment]
I know ss-local runs on my mac & ss-server runs on remote VPS.... I am not a noob...  

How I can debug it... or how I can trace it worked or not, on my mac setting or another command line?...

**Comment by FlowerWrong** [comment]
1. You can test the local dns server. `dig @127.0.0.1 google.com`, it will return a fake ip like `192.18.0.123` if it worked.
2. restart you local socks5 proxy with debug mode. `curl google.com` has log or not?
3. restart you remote proxy server with debug mode. `curl google.com` has log or not?

If you are familiar with `golang`, you can write some logs by yourself.

**Comment by FlowerWrong** [comment]
I am sorry. this app is not broken now.

**Comment by lgh06** [comment]
I will try.
