### ISSUE TITLE
cannot install on mac through go get -u -v github.com/FlowerWrong/tun2socks

### ISSUE THREAD

**Issue by daniel-fuelx** [FlowerWrong/tun2socks#46]
maybe should changed to  :  

go get -u -v github.com/FlowerWrong/tun2socks/...

**Comment by FlowerWrong** [comment]
I am sorry for this. My code is ugly. You can follow the [readme](https://github.com/FlowerWrong/tun2socks#how-to-use-it-more) step by step.
