### ISSUE TITLE
怎么启用udp_relay_via_socks5，config应该怎么定义

### ISSUE THREAD

**Issue by TOP666666** [FlowerWrong/tun2socks#50]
想自定义route，进行全局代理。请问应该怎么定义config？

**Comment by FlowerWrong** [comment]
1. [set dns-mode](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L20)
2. set your system dns server, eg `8.8.8.8`
3. set your route table, [eg](https://github.com/FlowerWrong/ip2socks/blob/master/scripts/darwin_setup_utun.sh#L3-L29)

**Comment by TOP666666** [comment]
https://github.com/FlowerWrong/ip2socks/blob/master/scripts/darwin_setup_utun.sh#L3-L29
windows下怎么使用？linux下的意思使用也是自己另外执行.sh脚本？

**Comment by FlowerWrong** [comment]
windows下得自己写了，linux下那个目录下就有参考。https://github.com/FlowerWrong/ip2socks/blob/master/scripts/linux_setup_tuntap.sh

**Comment by TOP666666** [comment]
那请问使用先用的config.ini能做出来全局代理吗？不是只代理域名，所有应用都通过代理出去

**Comment by FlowerWrong** [comment]
可以，fake mode简单点。udp_relay_via_socks5需要自己写入大量的route table。

**Comment by TOP666666** [comment]
自己定义的route table能通过config.ini载入执行吗？

**Comment by FlowerWrong** [comment]
可以是可以，但是量太大了，最好单独脚本执行。https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L39-L52

**Comment by TOP666666** [comment]
config.ini怎么载入外部脚本？ 或者在conifg.ini能定义 全局应用走代理B。 白名单的ip走自身网络

**Comment by FlowerWrong** [comment]
不能载入，请手动执行。
