### ISSUE TITLE
windows: gcc -o tun2socks main.c libtun2socks.lib

### ISSUE THREAD

**Issue by TOP666666** [FlowerWrong/tun2socks#52]
环境win7-64     git    tdm64-gcc-5.1.0-2      go
执行操作
windows: gcc -o tun2socks main.c libtun2socks.lib -l winmm -l ntdll -l Ws2_32

错误
main.c: In function 'tun2socksThread':
main.c:20:5: warning: implicit declaration of function 'GoStartTun2socks' [-Wimp
licit-function-declaration]
     GoStartTun2socks(configFile);
     ^
main.c: In function 'uiThread':
main.c:30:5: warning: implicit declaration of function 'GoReloadConfig' [-Wimpli
cit-function-declaration]
     GoReloadConfig(configFile);
     ^
C:\Users\ADMINI~1\AppData\Local\Temp\ccwUkBMZ.o:main.c:(.text+0x44): undefined r
eference to `GoStartTun2socks'
C:\Users\ADMINI~1\AppData\Local\Temp\ccwUkBMZ.o:main.c:(.text+0xad): undefined r
eference to `GoReloadConfig'
collect2.exe: error: ld returned 1 exit status

求帮助

**Comment by FlowerWrong** [comment]
sorry，我移除了支持。

**Comment by FlowerWrong** [comment]
如果需要，可以参考这个[commit](https://github.com/FlowerWrong/tun2socks/commit/5c2872faf24a8d95fb9bffa61916d59b50c447e7)
