### ISSUE TITLE
NAT Type Symmetric

### ISSUE THREAD

**Issue by sqwwqw5** [FlowerWrong/tun2socks#53]
Wonder if we could at least get a restricted cone with tun2socks?
BTW, your version is very easy to setup and go!

**Comment by sqwwqw5** [comment]
Check out outline, they used tun2socks and managed to get a restricted cone though I'm not happy with how they handle remote DNS and give very little configbility to users.

**Comment by FlowerWrong** [comment]
Of course you can, see https://github.com/FlowerWrong/tun2socks/issues/31.
`This project has no any license, you can use it to do what you want, but it has nothing to do with me.`
