### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by android0276** [FlowerWrong/tun2socks#54]
应用程序 -> tun -> Tun2sock -> 代理服务 -> 目标服务器
假如请求的域名是abc.com，abc.com 在 tun 这里会做DNS解析
想问下在代理服务器那里还会进行DNS再次查询请求吗

**Comment by android0276** [comment]
我知道http代理的dns都是在远程查询的，难道走TUN2sock到远程服务器这种也是需要的吗，需要做两次DNS查询

**Comment by FlowerWrong** [comment]
你用的是哪种模式在跑？
https://github.com/FlowerWrong/tun2socks/wiki#dns-mode

**Comment by android0276** [comment]
没有用fake-mode，用的纯路由那种

**Comment by android0276** [comment]
我用 Curl 调试过，确实不行

**Comment by android0276** [comment]
我发现我的经过 Tunsock 到远程代理服务器后重新解析DNS了

**Comment by android0276** [comment]
你走 fake-mode 的话，如果设置etc/hosts， 请求的时候将直接是IP，你的规则并不会代理这个，他会走直连

**Comment by android0276** [comment]
大神再分析下

**Comment by FlowerWrong** [comment]
不会吧，你`dig`看下dns对不对。后续走代理或者直连都没问题。

**Comment by android0276** [comment]
DNS 对的没有问题

**Comment by android0276** [comment]
![image](https://user-images.githubusercontent.com/8524130/51670197-16bc3500-2001-11e9-818f-e224a9eaa580.png)
![image](https://user-images.githubusercontent.com/8524130/51670217-20de3380-2001-11e9-8cb8-9c1ed6589b40.png)

**Comment by FlowerWrong** [comment]
`curl -i -v https://ourbits.club/torrents.php`
我这里还真没复现。

**Comment by android0276** [comment]
![image](https://user-images.githubusercontent.com/8524130/51670599-f93b9b00-2001-11e9-90aa-a53fb0acd8fc.png)
![image](https://user-images.githubusercontent.com/8524130/51670671-1bcdb400-2002-11e9-9349-8e91fcbfb750.png)
![image](https://user-images.githubusercontent.com/8524130/51670692-238d5880-2002-11e9-9ed8-3a326b59eca8.png)

**Comment by android0276** [comment]
你确认你的这个请求被代理了吗

**Comment by FlowerWrong** [comment]
我明儿用你那种模式试试。

**Comment by android0276** [comment]
好吧...tun2sock 转发TCP流量，代理服务器不会再解析DNS吧

**Comment by FlowerWrong** [comment]
我试了下，还是可以的。终端查询dns的时候用`dscacheutil -q host -a name ourbits.club`

> tun2sock 转发TCP流量，代理服务器不会再解析DNS吧

socks5代理支持三种，ipv4、ipv6和域名，如果是域名，那么肯定需要在代理服务器上解析，ip则不用。
https://zh.wikipedia.org/wiki/SOCKS#SOCKS5

这里应该还是/etc/hosts有没有起效的问题。我是darwin。

**Comment by android0276** [comment]
![image](https://user-images.githubusercontent.com/8524130/51721737-fb4b3b80-208d-11e9-83ff-bdbb892071bb.png)
还是不行。。。我必须 sudo route  51.15.167.112/32 我的默认网关才行

**Comment by FlowerWrong** [comment]
😢 我的route table
https://github.com/FlowerWrong/ip2socks/blob/master/scripts/darwin_setup_utun.sh

**Comment by android0276** [comment]
你的这个走的代理还是直连   51.15.167.112/32，我用的CNroute

**Comment by android0276** [comment]
你 traceroute 51.15.167.112 看下你走的啥

**Comment by android0276** [comment]
sudo route add 51.15.167.112/32  192.168.1.1 我是ok的，但是51.15.167.112是个国外IP

**Comment by android0276** [comment]
我觉得这个问题是个比较深的问题...

**Comment by android0276** [comment]
大神还需要我提供哪些信息，我这边都可以提供，只求帮忙解决这个问题，这个感觉是我的技术盲区，谢谢哈

**Comment by FlowerWrong** [comment]
我这里还是ok的。这个和走不走代理没有关系。都是ip访问，这里是dns出的问题。
```
sudo route -n add -host 51.15.167.112 -interface utun1
Password:
add host 51.15.167.112: gateway utun1
 ~  curl -i -v https://ourbits.club/torrents.php
*   Trying 51.15.167.112...
* TCP_NODELAY set
* Connected to ourbits.club (51.15.167.112) port 443 (#0)
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: ourbits.club
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /torrents.php HTTP/1.1
> Host: ourbits.club
> User-Agent: curl/7.63.0
> Accept: */*
>
< HTTP/1.1 302 Moved Temporarily
HTTP/1.1 302 Moved Temporarily
< Server: nginx
Server: nginx
< Date: Fri, 25 Jan 2019 03:41:42 GMT
Date: Fri, 25 Jan 2019 03:41:42 GMT
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Connection: keep-alive
Connection: keep-alive
< Location: /login.php?returnto=torrents.php
Location: /login.php?returnto=torrents.php
< Expires: Fri, 25 Jan 2019 15:41:42 GMT
Expires: Fri, 25 Jan 2019 15:41:42 GMT
< Cache-Control: max-age=43200
Cache-Control: max-age=43200
< X-Cache: MISS
X-Cache: MISS

<
* Connection #0 to host ourbits.club left intact
```

**Comment by FlowerWrong** [comment]
我没法复现，无法确定具体问题在哪里。

**Comment by FlowerWrong** [comment]
你试试 `curl --http1.1 -i -v https://ourbits.club/torrents.php`
我本地没有http2环境

**Comment by android0276** [comment]
![image](https://user-images.githubusercontent.com/8524130/51727313-6143bd00-20a6-11e9-8aaa-7730312b0e95.png)
![image](https://user-images.githubusercontent.com/8524130/51727320-6e60ac00-20a6-11e9-9714-50035739cb63.png)
还是不行

**Comment by android0276** [comment]
还需要提供其他数据供你分析吗

**Comment by FlowerWrong** [comment]
😭 这就很尴尬了。
你ssh到服务器上试试，改`/etc/hosts`，然后curl，我这里试了hk的服务器ok的。
如果你的也没问题，那么再看看ss日志，是不是代理的时候用的域名而不是ip地址。

**Comment by android0276** [comment]
有个奇怪的事情，我使用我自己的Vmess是ok的，而且发起请求的也是IP，可以正常工作。
![image](https://user-images.githubusercontent.com/8524130/51728764-4a07ce00-20ac-11e9-949a-5ce2e5a9cebb.png)
但是使用 ShadowsocksR节点就不行

**Comment by android0276** [comment]
话说我想不通。。Vmess是在本地弄个socks5   SSR也是弄个socks5，为啥Vmess可以，SSR死活都不行

**Comment by FlowerWrong** [comment]
我用的官方ss，你熟悉代码可以跟踪一下，多打打log。
我觉得不是什么大问题。

**Comment by android0276** [comment]
好吧，这个问题我不纠结了，我感觉是不是ssr 强制做了 tcp dns 重解析
