### ISSUE TITLE
Port type error while compiling

### ISSUE THREAD

**Issue by JayBitron** [FlowerWrong/tun2socks#56]
Hello,

I get this error while trying to compile using command `go get -u -v github.com/FlowerWrong/tun2socks/cmd`:
`src/github.com/FlowerWrong/tun2socks/util/port.go:10:26: cannot use func literal (type func(uint16) (bool, *"github.com/FlowerWrong/netstack/tcpip".Error)) as type func(uint16) (bool, *"github.com/google/netstack/tcpip".Error) in argument to stack.PortManager.PickEphemeralPort`.

any idea how to fix it?

Thanks.

**Comment by FlowerWrong** [comment]
May help you. https://github.com/FlowerWrong/tun2socks#note

**Comment by JayBitron** [comment]
I'm on linux so `go get -u -v github.com/FlowerWrong/tun2socks/cmd` should compile whatever provided as default.

**Comment by FlowerWrong** [comment]
Please checkout to [smart branch](https://github.com/FlowerWrong/netstack/tree/smart).

**Comment by JayBitron** [comment]
Please change sub repos of `FlowerWrong/proxy/cmd/tls/tls-gen` from `git@github.com:michaelklishin/tls-gen.git` to `https://github.com/michaelklishin/tls-gen` so people can fetch the whole software without ssh keys, that's the first. second of all please change `https://golang.org/x/sys` to `https://github.com/golang/sys` and `https://gopkg.in/gcfg.v1` to `https://github.com/go-gcfg/gcfg` branch v1, due to US sanctions on some countries I get 403 access denied in restricted countries on google domains; And the final, please make a unix branch to `tun2socks` to we can get a binary out of `go get -u -v github.com/FlowerWrong/tun2socks/cmd`. Thanks.

**Comment by JayBitron** [comment]
Also the latest release that you just provided that says latest stable 1.0 says it's version 0.5 in command line.

**Comment by FlowerWrong** [comment]
https://github.com/FlowerWrong/proxy/commit/69701a38960b7b10bb8a9593693f052b0139cd6b tls removed

**Comment by FlowerWrong** [comment]
https://github.com/FlowerWrong/tun2socks/releases changed to v0.5

**Comment by JayBitron** [comment]
There was a v0.5.
