### ISSUE TITLE
[question]how to socksify ipaddress.

### ISSUE THREAD

**Issue by syfy** [FlowerWrong/tun2socks#58]
hi i want to socksify some ipaddr non name servers webpage. i tried to use 
[pattern "proxy-website-ipcidr"] on config.ini but  tun2socks uses direct internet connection.

**Comment by FlowerWrong** [comment]
ipcidr and geoip are based on dns. For example, example.com's dns query response is `45.67.89.0`, if you add `45.67.89.0/32` to proxy ipcidr, this domain will be route to proxy. So, if you want to route static ip to proxy, you should use route table, [eg](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L38-L52).

**Comment by syfy** [comment]
> ipcidr and geoip are based on dns. For example, example.com's dns query response is `45.67.89.0`, if you add `45.67.89.0/32` to proxy ipcidr, this domain will be route to proxy. So, if you want to route static ip to proxy, you should use route table, [eg](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L38-L52).

how about to socksify  some games with no domain name tcp://1.2.3.4:444
is there a chance to do it here in tun2socks

**Comment by FlowerWrong** [comment]
```
[route]
# eg: sudo ip route add 91.108.4.0/22 dev tun0
# If you have large route tables, please add it with route batch mode by yourself,
# or it will take a long time.
# batch mode:
#   linux -> `ip -batch`
#   osx -> @see https://github.com/FlowerWrong/ip2socks/blob/master/scripts/darwin_setup_utun.sh#L14-L16
v = 198.18.0.0/15
v = 91.108.4.0/22
v = 91.108.56.0/22
v = 109.239.140.0/24
v = 149.154.160.0/20
v = 149.154.167.0/24
v = 8.8.8.8
v = 4.4.4.4
v = 1.2.3.4 # note the last line
```

**Comment by syfy** [comment]
thanks it worked in linux. ill try to do it in windows
