### ISSUE TITLE
stack.go:56:23: not enough arguments in call to fdbased.New

### ISSUE THREAD

**Issue by lgh06** [FlowerWrong/tun2socks#59]
```
sudo go run /Users/xxgov/go/src/github.com/FlowerWrong/tun2socks/cmd/main.go -c=/Users/xxgov/go/src/github.com/FlowerWrong/tun2socks/config.ini

go/src/github.com/FlowerWrong/tun2socks/tun2socks/stack.go:56:23: not enough arguments in call to fdbased.New
	have (*fdbased.Options)
	want (*water.Interface, *fdbased.Options)
go/src/github.com/FlowerWrong/tun2socks/tun2socks/stack.go:61:3: unknown field 'PacketDispatchMode' in struct literal of type fdbased.Options
go/src/github.com/FlowerWrong/tun2socks/tun2socks/stack.go:75:4: cannot use tcpip.AddressMask(strings.Repeat("\x00", len(addr))) (type tcpip.AddressMask) as type tcpip.Address in field value
go/src/github.com/FlowerWrong/tun2socks/tun2socks/tcp2socks.go:212:16: assignment mismatch: 3 variables but 2 values
```

**Comment by lgh06** [comment]
go version go1.11.1 darwin/amd64

**Comment by lgh06** [comment]
go get ./...
# github.com/FlowerWrong/tun2socks/tun2socks
./stack.go:56:23: not enough arguments in call to fdbased.New
	have (*fdbased.Options)
	want (*water.Interface, *fdbased.Options)
./stack.go:61:3: unknown field 'PacketDispatchMode' in struct literal of type fdbased.Options
./stack.go:75:4: cannot use tcpip.AddressMask(strings.Repeat("\x00", len(addr))) (type tcpip.AddressMask) as type tcpip.Address in field value
./tcp2socks.go:212:16: assignment mismatch: 3 variables but 2 values

**Comment by FlowerWrong** [comment]
Please use smart branch https://github.com/FlowerWrong/tun2socks#note

**Comment by lgh06** [comment]
@FlowerWrong Put  smart branch's netstack to which directory? I need more details……

**Comment by FlowerWrong** [comment]
https://github.com/FlowerWrong/netstack/tree/smart

**Comment by lgh06** [comment]
I went to the /Users/xxgov/go/src/github.com/FlowerWrong/netstack directory and fetched the smart branch and go get ./... , no error accured.
But seems faced dns problems. I am looking into that.
