### ISSUE TITLE
tun2socks_windows.exe是64位的，麻烦再提供一个32位的版本

### ISSUE THREAD

**Issue by zdm2008** [FlowerWrong/tun2socks#6]
tun2socks_windows.exe是64位的，麻烦再提供一个32位的版本，谢谢。

**Comment by FlowerWrong** [comment]
windows版本可用吗？我没有进行更多的windows测试，平时也不用windows

**Comment by FlowerWrong** [comment]
@zdm2008 windows 32bit [tun2socks 0.3](https://github.com/FlowerWrong/tun2socks/releases/tag/0.3)

**Comment by zdm2008** [comment]
目前在windows10下可以用，但是在windows7下不能用，错误代码如下：

2018/01/20 11:27:47 main.go:26: Use CPU number 4
2018/01/20 11:27:47 main.go:42: config file is config.ini
2018/01/20 11:27:47 proxies.go:62: [proxies] default proxy: "B"
2018/01/20 11:27:47 tun_windows.go:33: Interface Name: SSTAP 1
2018/01/20 11:27:47 cmd.go:14: exec command: netsh interface ip set address "SSTAP 1" static 198.18.0.0 255.254.0.0 none
2018/01/20 11:27:50 cmd.go:14: exec command: netsh interface ipv4 add dnsserver "以太网" 127.0.0.1 index=1
2018/01/20 11:27:50 main.go:80: Http pprof listen on 127.0.0.1:6060  see http://127.0.0.1:6060/debug/pprof/
2018/01/20 11:27:50 dns.go:124: execCommand failed exit status 1
2018/01/20 11:27:50 fake.go:187: [dns] listen on 0.0.0.0:53

**Comment by zdm2008** [comment]
麻烦您测试并支持windows平台，linux平台网上已经有好多成熟的产品了，所以windows平台的价值绝对比较大。

**Comment by FlowerWrong** [comment]
win7下面有闪退吗？还是只是说不能用？
我看了下错误，Windows下自动设置dns的时候失败了，因为我默认接口写的是“以太网”, see [these lines](https://github.com/FlowerWrong/tun2socks/blob/master/util/dns.go#L116-L125)，你可以手动把当前网络接口（非tap-windows接口）的dns设置成`127.0.0.1`.

**Comment by zdm2008** [comment]
win7和win10下都没有闪退，根据你的提示已将本地网卡改为127.0.0.1之后，可以正常打开脸书和谷歌了，谢谢。
麻烦您再改进一下这个问题，避免手动设置DNS，应该就好了。

**Comment by FlowerWrong** [comment]
@zdm2008 fixed at [0.4 version](https://github.com/FlowerWrong/tun2socks/releases/tag/0.4)
