### ISSUE TITLE
你好，可以咨询你一下关于TAP-Windows的问题？

### ISSUE THREAD

**Issue by liulilittle** [FlowerWrong/tun2socks#67]
如何解决TAP设备在读写一段时间后（多为下载文件流时）应用层无法向TAP之中写入IP数据包或者从中读入IP数据包。

How to solve the problem that the TAP device cannot write IP packets to or read IP packets from the TAP application layer after reading and writing for a period of time (mostly when downloading a file stream).

**Comment by FlowerWrong** [comment]
我好多年不用windows了，有错误信息吗？

**Comment by liulilittle** [comment]
并没有发现任何的错误，但是无法在从TAP设备之中读入IP数据包，同时也无法在写入的IP数据包（虽然调用WriteFile是确定写入到TAP设备的）
如果想要恢复只需要重启TAP设备就可以，但是这样会造成运行TAP设备的主机系统会杀掉与之关联的链接。

**Comment by FlowerWrong** [comment]
抱歉，没有思路

**Comment by liulilittle** [comment]
好的，谢谢！
