### ISSUE TITLE
关于DNS设置有两个问题需要反馈一下

### ISSUE THREAD

**Issue by zdm2008** [FlowerWrong/tun2socks#7]
1、在windows下运行cmd程序，正常关闭之后127.0.0.1并没有还原DNS设置，导致上不了网。
2、在windows多网卡的环境下，自动设置的DNS没有正确识别出口网卡，导致设置无效。

错误设置DNS的日志如下，设置修改到VMware的虚拟网卡上了：
C:\Users\Simon Zhou\Desktop>tun2socks_windows_32.exe --config=config.ini
2018/01/23 01:53:34 main.go:23: Use CPU number 4
2018/01/23 01:53:34 main.go:39: config file is config.ini
2018/01/23 01:53:34 proxies.go:62: [proxies] default proxy: "B"
2018/01/23 01:53:34 tun_windows.go:33: Interface Name: SSTAP 1
2018/01/23 01:53:34 cmd.go:14: exec command: netsh interface ip set address "SSTAP 1" static 198.18.0.0 255.254.0.0 none
2018/01/23 01:53:37 main.go:77: Http pprof listen on 127.0.0.1:6060  see http://127.0.0.1:6060/debug/pprof/
2018/01/23 01:53:37 app.go:216: {23 1500 SSTAP 1 00:ff:f9:a5:25:21 up|broadcast|multicast}
2018/01/23 01:53:37 app.go:216: {19 1500 本地连接* 12 7a:31:c1:bb:ff:34 broadcast|multicast}
2018/01/23 01:53:37 app.go:216: {3 1500 本地连接* 15 78:31:c1:bb:ff:34 broadcast|multicast}
2018/01/23 01:53:37 app.go:216: {15 1500 VMware Network Adapter VMnet1 00:50:56:c0:00:01 up|broadcast|multicast}
2018/01/23 01:53:37 app.go:216: {22 1500 VMware Network Adapter VMnet8 00:50:56:c0:00:08 up|broadcast|multicast}
2018/01/23 01:53:37 app.go:216: {10 1500 本地连接* 13 00:ff:6a:0b:6b:28 broadcast|multicast}
2018/01/23 01:53:37 app.go:216: {1 -1 Loopback Pseudo-Interface 1  up|loopback|multicast}
2018/01/23 01:53:37 app.go:216: {11 1500 WLAN 78:31:c1:bb:ff:34 up|broadcast|multicast}
2018/01/23 01:53:37 cmd.go:14: exec command: netsh interface ip set dns name="VMware Network Adapter VMnet1" source=static addr=127.0.0.1 register=primary
2018/01/23 01:53:45 fake.go:187: [dns] listen on 0.0.0.0:53

**Comment by FlowerWrong** [comment]
1. 这个有日志吗？我用的时候可以正确还原
2. 多网口目前没有办法，要么把网口写到配置文件，或者启动的时候让他选择网口

**Comment by FlowerWrong** [comment]
另外，多网口的时候，运行netsh interface show interface显示什么？

**Comment by zdm2008** [comment]
日志已经贴在上面了，具体如下：
2018/01/23 01:53:37 cmd.go:14: exec command: netsh interface ip set dns name="VMware Network Adapter VMnet1" source=static addr=127.0.0.1 register=primary

VMware Network Adapter VMnet1这个是VMware的虚拟网卡，你把DNS设置到这个上面了。


cmd运行netsh interface show interface显示内容如下：
C:\WINDOWS\system32>netsh interface show interface

管理员状态     状态           类型             接口名称
-------------------------------------------------------------------------
已启用            已断开连接          专用               SSTAP 1
已启用            已连接            专用               VMware Network Adapter VMnet1
已启用            已连接            专用               VMware Network Adapter VMnet8
已启用            已连接            专用               WLAN

**Comment by FlowerWrong** [comment]
如果是单网卡，第一个第二个问题都不存在。第二个问题目前没有好的解决方案，写到配置文件里面也很麻烦，如果是多网口，我试着做成弹出窗，让用户自己选择。

**Comment by zdm2008** [comment]
最好的方案是写到配置文件里面，让用户自己配置

**Comment by zdm2008** [comment]
或者改成输入参数，启动的时候传进去。

**Comment by FlowerWrong** [comment]
I just add a config prop named `interface` to fix this, default auto config, see [config.ini](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L11) at [release 0.5](https://github.com/FlowerWrong/tun2socks/releases/tag/0.5)
