### ISSUE TITLE
咨询c static library如何使用

### ISSUE THREAD

**Issue by zdm2008** [FlowerWrong/tun2socks#8]
非常感谢提供c static library，有两个问题请教一下：

1、c static library可不可以提供一个win 32位的lib版本？
2、c static library怎么使用，可否提供api说明或demo？

**Comment by FlowerWrong** [comment]
https://github.com/FlowerWrong/tun2socks/blob/master/README.md#as-a-static-library

32位的是交叉编译的，不知道对不对，所以没有放。

c库目前只会是导出了一个函数

**Comment by FlowerWrong** [comment]
[libtun2socks for windows 32 bit](https://github.com/FlowerWrong/tun2socks/releases/tag/0.5). I have tested it.

**Comment by zdm2008** [comment]
可以提供一个简单的c/c++语言如何使用的demo代码吗？

**Comment by zdm2008** [comment]
调用RunTun2socks程序之后，如果不退出自身的程序，如何关闭/断开Tun2socks程序？

**Comment by FlowerWrong** [comment]
demo已经给了，请仔细看readme和wiki。后续会导出更多的c api接口。
