### ISSUE TITLE
请帮忙看这一段日志是怎么回事？

### ISSUE THREAD

**Issue by zdm2008** [FlowerWrong/tun2socks#9]
问题：不能上网，显示DNS解析失败？

2018/01/25 01:45:51 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:45:51 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:45:51 fake.go:53: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: code 2
2018/01/25 01:45:51 fake.go:53: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: code 2
2018/01/25 01:45:51 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:45:51 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:45:53 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:45:53 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:45:53 fake.go:53: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: code 2
2018/01/25 01:45:53 fake.go:53: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: code 2
2018/01/25 01:45:53 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:45:53 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:45:55 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:45:55 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:45:57 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:45:57 fake.go:53: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: code 2
2018/01/25 01:45:58 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:45:58 fake.go:53: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: code 2
2018/01/25 01:46:00 fake.go:48: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: read udp 192.168.2.103:60881->223.5.5.5:53: i/o timeout
2018/01/25 01:46:00 fake.go:48: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: read udp 192.168.2.103:60882->223.5.5.5:53: i/o timeout
2018/01/25 01:46:01 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:46:01 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:46:01 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:46:01 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:46:03 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:46:03 fake.go:53: [dns] resolve client.wns.windows.com. on 114.114.114.114:53 failed: code 2
2018/01/25 01:46:03 fake.go:53: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: code 2
2018/01/25 01:46:03 fake.go:53: [dns] resolve client.wns.windows.com. on 223.5.5.5:53 failed: code 2
2018/01/25 01:46:03 fake.go:84: [dns] query client.wns.windows.com. failed
2018/01/25 01:46:04 fake.go:84: [dns] query client.wns.windows.com. failed

**Comment by FlowerWrong** [comment]
关掉后可以上网吗

**Comment by zdm2008** [comment]
关掉后必须手动将主网卡的127.0.0.1这个DNS记录修改为自动获取才可以上网。

**Comment by FlowerWrong** [comment]
目前没有出现过这个问题，我猜可能是网络出问题了，或者默认配置的dns不适合你。你可以自行修改[配置文件](https://github.com/FlowerWrong/tun2socks/blob/master/config.example.ini#L26)

**Comment by zdm2008** [comment]
还有这个tcp的错误，麻烦您看一下。

2018/01/25 15:31:43 tcp2socks.go:155: Write packet to remote failed write tcp 127.0.0.1:19608->127.0.0.1:1080: wsasend: An established connection was aborted by the software in your host machine. bank.hangseng.com:443
2018/01/25 15:32:03 tcp2socks.go:155: Write packet to remote failed write tcp 127.0.0.1:19825->127.0.0.1:1080: wsasend: An established connection was aborted by the software in your host machine. bank.hangseng.com:443
2018/01/25 15:32:03 tcp2socks.go:155: Write packet to remote failed write tcp 127.0.0.1:19819->127.0.0.1:1080: wsasend: An established connection was aborted by the software in your host machine. bank.hangseng.com:443

**Comment by FlowerWrong** [comment]
@zdm2008 该错误在三个端都存在，目前没有找到原因，但是不影响使用。我会继续跟进。

**Comment by FlowerWrong** [comment]
see [issue 10](https://github.com/FlowerWrong/tun2socks/issues/10)

**Comment by zdm2008** [comment]
会影响使用的，页面打不开，会导致所有的网页卡在那里，但是过一会这个网页居然又能打开了？

**Comment by FlowerWrong** [comment]
应该不是这个问题导致的。这个问题主要是由于对端timeout关掉了连接。所有网页卡这个看看是不是网络问题。

**Comment by FlowerWrong** [comment]
@zdm2008 似乎是因为windows cmd.exe会阻塞golang的日志，在cmd.exe多敲几下回车，把没有显示的日志打印出来就好了。

**Comment by LuoZijun** [comment]
@FlowerWrong 如果是这样， Windows 下面的 Log 写在文件而不是 Shell 的缓冲区 是不是更好？

**Comment by FlowerWrong** [comment]
@LuoZijun 这个问题还没有确定？需要更多的测试确定问题所在。在linux和mac下没这个问题。
